# Generated by Django 3.1.1 on 2020-10-26 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=12)),
                ('zipcode', models.IntegerField(null=True)),
                ('dob', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=20)),
                            ],
        ),
    ]
