# Generated by Django 3.1.1 on 2020-09-30 02:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=12)),
                ('zipcode', models.IntegerField(max_length=5)),
                ('dob', models.DateTimeField(max_length=8)),
                ('phone', phone_field.models.PhoneField(max_length=15)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
