# Generated by Django 3.1.1 on 2020-09-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
