# Generated by Django 3.1.1 on 2020-10-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200930_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='f_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='l_name',
            new_name='lname',
        ),
    ]
