# Generated by Django 3.1.1 on 2020-10-29 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userinfo'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userinfo'),
        ),
    ]
