# Generated by Django 3.1.1 on 2020-10-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201001_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
