# Generated by Django 3.1.1 on 2020-10-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201029_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bamount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
    ]
