# Generated by Django 3.1.3 on 2020-11-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201113_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='brecipient',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
